# -*- coding: utf-8 -*-
"""credit_scoring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OUFecNzeMaik1qoembdMaq0h7vZ-Vb_l

#Credit Scoring Model

#Project Problem Statement
The goal of this project is to build a machine learning model that predicts a customer's credit risk level using financial history, income, debt behavior, and payment patterns.

###kaggle link for the dataset
https://www.kaggle.com/datasets/programmer3/credit-worthiness-assessment-dataset

| Feature Name                       | Meaning                                                |
| ---------------------------------- | ------------------------------------------------------ |
| `Age`                              | Age of the customer                                    |
| `Gender`                           | Gender of the customer                                 |
| `Marital_Status`                   | Whether customer is married/single/divorced            |
| `Dependents`                       | Number of people financially dependent on the customer |
| `Employment_Length`                | Number of years customer has been employed             |
| `Monthly_Income`                   | Monthly salary/income of the customer                  |
| `Annual_Income_Growth`             | Yearly growth in income                                |
| `Job_Stability_Index`              | Measures stability of employment/job                   |
| `Monthly_Pension_Contribution`     | Monthly amount contributed to pension/savings          |
| `Years_Pension_Savings`            | Number of years contributing to pension                |
| `Pension_Balance`                  | Total pension savings amount                           |
| `Withdrawal_Frequency`             | How often money is withdrawn from savings/pension      |
| `Pension_Return_Rate`              | Returns/profit earned from pension investments         |
| `Contribution_Ratio`               | Percentage of income contributed toward savings        |
| `Contribution_Regularity`          | Consistency of savings contributions                   |
| `Credit_History_Length`            | Length of customer’s credit history                    |
| `Number_of_Loans`                  | Total number of loans taken by customer                |
| `Debt_to_Income_Ratio`             | Debt amount compared to income                         |
| `Credit_Utilization_Rate`          | Percentage of credit limit currently being used        |
| `Missed_Payments_Last_12M`         | Number of missed payments in last 12 months            |
| `EMI_to_Income_Ratio`              | Percentage of income used for EMI payments             |
| `Savings_to_Income_Ratio`          | Savings amount compared to income                      |
| `Spending_Volatility_Index`        | Measures irregularity in spending behavior             |
| `Investment_Diversification_Score` | Measures diversification of investments                |
| `Risk_Appetite_Index`              | Indicates customer’s financial risk-taking behavior    |
| `Emergency_Fund_Months`            | Number of months customer can survive without income   |
| `Transaction_Consistency_Index`    | Measures consistency of financial transactions         |
| `Credit_Risk_Level`                | Target column showing customer credit risk category    |

##Usually these below features become highly important:

Debt_to_Income_Ratio

Missed_Payments_Last_12M

Credit_Utilization_Rate

EMI_to_Income_Ratio

Credit_History_Length

Monthly_Income

Job_Stability_Index

##Step 1 — Import Libraries
"""

#Data Handling
import pandas as pd
import numpy as np

#Data visualization
import matplotlib.pyplot as plt
import seaborn as sns

#Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

#SMOTE
from imblearn.over_sampling import SMOTE

#pipeline
from sklearn.pipeline import Pipeline

#Models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

#Evaluation
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve

"""##Step 2 — Load Dataset"""

df = pd.read_csv("Pension_Credit_Assessment.csv")

"""##Step 3 — View Dataset"""

print(df.head())

"""##Step 4 — Check Dataset Shape

"""

print('original dataset shape: ',df.shape)

"""##Step 5 — Check Column Names"""

print(df.columns)

"""##Step 6 — Dataset Information"""

print(df.info())

"""##Step 7 — Check Missing Values"""

print(df.isnull().sum())

"""##Step 8 — Check Duplicate Rows"""

print(df.duplicated().sum())

"""##Step 9 — Basic Statistics

"""

print(df.describe())

"""##Step 10 — Check Target Variable Distribution"""

print(df['Credit_Risk_Level'].value_counts())

"""##Encoding"""

df['Credit_Risk_Level'] = df['Credit_Risk_Level'].replace({
    1: 0,
    2: 0,
    3: 1
})
print(df['Credit_Risk_Level'].value_counts())

"""##Step 11 — Visualize Target Classes"""

sns.countplot(x = 'Credit_Risk_Level', data = df)
plt.title("credit risk level distribution")
plt.savefig(
    "visualizations/target_distribution.png",
    bbox_inches="tight"
)
plt.show()

"""This graph shows the class imbalance in the target variable.

###Why This Is Important

If data is imbalanced:

model may become biased
model may predict majority class most of the time
accuracy alone becomes misleading

Example:

If 90% data belongs to class 3,
model may predict only class 3 and still get high accuracy.

But this is not a good model.

#Data Preprocessing
"""

for col in df.columns:
  print(f"\n column: {col}")
  print(df[col].unique())

"""There are no categorical columns here.All are numerical columns only.

##Step 13 — Feature Engineering

Now we create new meaningful financial features.

These help the model learn better patterns.
"""

df.columns

#financial burden score
df['financial_burden_score'] = (
    df['Debt_to_Income_Ratio']+
    df['EMI_to_Income_Ratio']+
    df['Missed_Payments_Last_12M']+
    df['Number_of_Loans']
) #This combines:debt burden,EMI burden,payment problems
  #Higher score = financially risky customer.

#savings strength
df['savings_strength'] = (
    df['Savings_to_Income_Ratio']+
    df['Emergency_Fund_Months']
)  #Customer with:high savings,good emergency fund is financially safer.

#credit discipline score
df['Credit_Discipline_Score'] = (
    df['Contribution_Regularity'] +
    df['Transaction_Consistency_Index']
)
#Measures:financial discipline,consistency,responsible behaviour

"""##Step 14 — Feature Selection Using Correlation"""

corr_matrix = df.corr()

#Visualize Correlation
plt.figure(figsize=(18,10))
sns.heatmap(corr_matrix[['Credit_Risk_Level']].sort_values(by='Credit_Risk_Level', ascending=False), cmap='coolwarm',annot=True)
plt.title('correlation matrix')
plt.savefig(
    "visualizations/correlation_heatmap.png",
    bbox_inches="tight"
)
plt.show()

"""Some features will have:

strong positive correlation
strong negative correlation

Those are important for prediction.

##Step 15 — Choose Top Features
"""

df.columns

selected_features = ['Debt_to_Income_Ratio',
                     'Withdrawal_Frequency',
                     'Missed_Payments_Last_12M',
                     'Credit_Utilization_Rate',
                     'financial_burden_score',
                     'EMI_to_Income_Ratio',
                      'Monthly_Income'
                     ]

"""###Outlier Detection"""

#Boxplot
plt.figure(figsize=(12,6))
sns.boxplot(data = df[selected_features])
plt.xticks(rotation=45)
plt.title("Outlier Detection using Box-plot")
plt.show()

#outlier removal
Q1 = df['Monthly_Income'].quantile(0.25)
Q3 = df['Monthly_Income'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[(df['Monthly_Income'] >= lower) & (df['Monthly_Income'] <= upper)]
print('dataset shape after removal of outliers: ',df.shape)

"""##Step 16 — Separate Features and Target"""

X = df[selected_features]
y = df['Credit_Risk_Level']

"""##Step 17 — Train Test Split"""

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size = 0.2, random_state = 42, stratify = y)

"""##Step 18 - Handling Imbalanced data using SMOTE"""

smote = SMOTE(random_state = 42)
X_train_smote,y_train_smote = smote.fit_resample(X_train, y_train)

print('Target classification after SMOTE:\n',y_train_smote.value_counts())

"""##Step 19 — Build Pipeline

"""

pipeline_log = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression(class_weight='balanced'))
])

"""##Step 20-Train model"""

pipeline_log.fit(X_train_smote,y_train_smote)

"""##Step 21 — Predictions"""

y_pred = pipeline_log.predict(X_test)

"""##Step 22 — Evaluate Model"""

accuracy = accuracy_score(y_test, y_pred)

print('Accuracy = ',accuracy)
print('Precision = ',precision_score(y_test,y_pred))
print('Recall = ',recall_score(y_test,y_pred))
print('F1 Score = ',f1_score(y_test,y_pred))

print('classification report:\n ',classification_report(y_test, y_pred))

"""###Class 0 (Safe / Moderate Risk Customers)
- Precision = 0.62
When the model predicts a customer as safe/moderate, it is correct 63% of the time
- Recall = 0.84
The model correctly identified 82% of actual safe/moderate customers
- F1-score = 0.71
Indicates moderately good performance for class 0

###Class 1 (High Risk Customers)
- Precision = 0.96
When the model predicts a customer as risky, it is correct 96% of the time
- Recall = 0.89
The model correctly identified 90% of actual risky customers
- F1-score = 0.93
Excellent balance between precision and recall
Indicates strong performance for risky customer prediction

##Interpretation
- The model performs very well overall
- It is especially strong at detecting risky customers
- High recall for risky customers is important in credit scoring because banks want to minimize loan defaults
- Converting the problem into binary classification improved performance significantly compared to the original multiclass setup

###confusion matrix
"""

print('Confusion Matrix: \n',confusion_matrix(y_test, y_pred))

"""####Important Interpretation for Credit Scoring
Good Signs

High TP = 811

The model is good at identifying trustworthy customers.

Low FP = 31

Very important in banking because fewer risky customers are approved.

####Concern

FN = 97

The model is rejecting some genuinely good customers.

This affects:

- customer satisfaction
- business opportunities
- loan approvals

##ROC-AUC curve and score

###Get Prediction Probabilities
"""

y_prob = pipeline_log.predict_proba(X_test)[:,1]

"""###Calculate ROC-AUC Score"""

roc_auc = roc_auc_score(y_test, y_prob)
print('ROC-AUC Score : ',roc_auc)

"""####Why ROC-AUC is Important in Credit Scoring
- Credit scoring datasets are usually imbalanced
Accuracy alone may be misleading
- ROC-AUC evaluates:
how well the model separates risky and safe customers

###Generate ROC Curve
"""

fpr, tpr, thresholds = roc_curve(y_test, y_prob)

"""###plot ROC Curve"""

plt.figure(figsize = (5,5))
plt.plot(fpr, tpr, label='ROC Curve')
plt.plot([0,1],[0,1],linestyle = '--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title('ROC Curve(Logistic Regression)')
plt.legend()
plt.savefig(
    "visualizations/logistic_regression_roc_curve.png",
    bbox_inches="tight"
)
plt.show()

"""- roc_curve() computes false positive rates and true positive rates at different probability thresholds, which are then used to plot the ROC curve and evaluate the model’s classification performance.
- Curve bends strongly toward top-left corner
Indicates strong class separation
Most good ML models look like this
- A strong ROC-AUC score indicated excellent class separation capability
- ROC-AUC evaluation was especially important because the dataset was imbalanced
- Overall, the model demonstrated strong performance in identifying high-risk customers and can be useful for credit risk assessment and loan approval decision-making systems

#Random Forest classifier

###Random Forest Pipeline
"""

pipeline_rf = Pipeline([
    ('model',RandomForestClassifier(
        n_estimators=100,
        random_state = 42,
        class_weight = 'balanced'
    ))
])

"""Random forest classifier does not need scaling as it is tree based model."""

pipeline_rf.fit(X_train_smote, y_train_smote)

"""###predict on original test data"""

y_pred_rf = pipeline_rf.predict(X_test)

"""###Accuracy"""

print('Accuracy: ',accuracy_score(y_test, y_pred_rf))
print('Precision: ',precision_score(y_test,y_pred_rf))
print('Recall: ',recall_score(y_test,y_pred_rf))
print('F1 Score: ',f1_score(y_test,y_pred_rf))

"""###classification report"""

print('classification report:\n ',classification_report(y_test, y_pred_rf))

"""###confusion matrix"""

print('confusion matrix using random forest classifier: \n',confusion_matrix(y_test, y_pred_rf))

"""###Explanation

1. True Negatives (TN) = 142

Model correctly identified:

bad/risky customers.

These customers were correctly predicted as loan defaulters or risky applicants.

2. False Positives (FP) = 47

Model predicted:

customers as good, but they were actually risky.

This is the most dangerous error in credit scoring because:

bank may approve risky loans
financial loss can occur

3. False Negatives (FN) = 82

Model predicted:

customers as risky, but they were actually good customers.

This means:

some genuine customers may get rejected
business opportunities are lost

But this random forest classifier model is better when compared to logistic regression model's values.

###ROC-AUC score and curve
"""

y_prob_rf = pipeline_rf.predict_proba(X_test)[:,1]

roc_auc = roc_auc_score(y_test, y_prob_rf)
print("ROC-AUC Score: ",roc_auc)

fpr,tpr,thresholds = roc_curve(y_test,y_prob_rf)

plt.figure(figsize=(5,4))
plt.plot(fpr, tpr, label='ROC Curve using Random Forest Classifier')
plt.plot([0,1],[0,1],linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve(Random Forest Classifier)')
plt.legend()
plt.savefig(
    "visualizations/random_forest_roc_curve.png",
    bbox_inches="tight"
)
plt.show()

"""The graph shows high tpr and low fpr that means it distiguishes well between two classes.

###By using logistic regression as model we get credit risk level's
- Accuracy = 0.8854545454545455
- Precision = 0.960093896713615
- Recall = 0.8989010989010989
- F1 Score = 0.9284903518728718
- ROC-AUC Score = 0.9458473105841527

###By using Random Forest Classifier as model we get credit risk level's
- Accuracy =  0.8945454545454545
- Precision =  0.9490950226244343
- Recall =  0.921978021978022
- F1 Score =  0.935340022296544
- ROC-AUC Score =  0.9382562174667438

-- On comparing both logistic regression and random forest classifier we get 2% of improvement in recall by using random forest classifier.

-- when we consider recall as the best factor to what amount of predicted credit riskers are correct compared to all true credit riskers, we have to choose Random Forest Classifier as our final model.
"""

import joblib

joblib.dump(
    pipeline_rf,
    "credit_scoring_model.pkl"
)

print("Model saved successfully!")
